sudo: required
services:
  - docker

before_install:
  - docker build -t hakanerdemtemiz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hakanerdemtemiz/docker-react npm run test

deploy:
  provider: elesticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-395328297768"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
